[sssd]
domains = MYDOM1.NET
config_file_version = 2
services = nss, pam
debug_level = 5


[domain/MYDOM1.NET]
access_provider = ad
id_provider = ad
ad_domain = MYDOM1.NET
ad_update_samba_machine_account_password = True
krb5_realm = MYDOM1.NET
krb5_store_password_if_offline = True
realmd_tags = manages-system joined-with-samba 


#####	DOMAIN OPTIONS	#####

#
### (common)
cache_credentials = True
default_shell = /bin/bash

#
### enumerate
##	w/a large number of AD objects, you may want to disable enumeration for quick post-boot login
enumerate = true

#
### use_fully_qualified_names
##	False tells SSSD to not append the domain to the username, solving a lot of issues
##	NOTE:  May affect other values -- e.g., fallback_homedir
# NO # use_fully_qualified_names = True
use_fully_qualified_names = False
# NO # fallback_homedir = /home/%u@%d
fallback_homedir = /home/%u

#
### ldap_id_mapping
##	False tells SSSD to use the native AD IETF2307bis schema 
##	From 'man 5 sssd-ldap' ...
##	    ldap_id_mapping (boolean)
##		Specifies that SSSD should attempt to map user and group IDs from the
##		ldap_user_objectsid and ldap_group_objectsid attributes instead of
##		relying on ldap_user_uid_number and ldap_group_gid_number.
ldap_id_mapping = False

#
### AD-specific (not IETF) Dynamic DNS?
#
# NO # dyndns_refresh_interval = 43200
# NO # dyndns_update_ptr = false
# NO # dyndns_ttl = 3600

