#
#	/etc/samba.pre/smb.conf
#

#####	GLOBAL	#####

[global]
    workgroup = MYDOM1
    security = user
    kerberos method = secrets
	server string = Samba Server Version %v
	machine password timeout = 0

#
### Options
#
    template homedir = /storage/home/%U
    server string = Samba Server Version %v
    log file = /var/log/samba/log.%m
	max log size = 8192
	log level = 5

#
### idmap config (local default)
    idmap config * : range = 10000000-10999999
## do NOT touch
# tdb
    idmap config * : backend = tdb

#
### Legacy Security
## (use v4.x auto-defaults or issues might arise)
#
# D #	lanman auth = no
# D #	encrypt passwords = yes
# D #	client use spnego = yes
# D #	client lanman auth = no
#	client ntlmv2 auth = yes
#	server signing = mandatory
#	#server signing = auto
#	client signing = mandatory
#	#client signing = auto
#	client ldap sasl wrapping = seal
#	password server = dc01.MYDOM1.NET
#	password server = dc02.MYDOM1.NET

#
### Printing
## (disabled)
#
	load printers = no
	printing = bsd
	printcap name = /dev/null
	disable spoolss = yes


#####	SHARES	#####

