---
#
#	./nvidia/defaults/main.yml
#


#####	DEFAULTS

###     nVidia driver - this should be DKMS and a DataCenter certified driver release
# SEE:  https://docs.nvidia.com/datacenter/tesla/index.html
# CUR:  As of 2025Q2, this is R570 (570-dkms) w/CUDA 12.8

###     COMMON (to all EL)

# nVidia dependencies Software
defSWelX_nvidia_deps:
  - "@development"
  - dkms
  - kernel-devel

# nVidia CUDA releases -- use latest DC certified minor releases + final previous release
defSWelX_nvidia_cuda:  
  - cuda-11-8.x86_64    # Final CUDA 11 release
# DC #  - cuda-12-0.x86_64        # R525 (DataCenter Certified) - initial CUDA 12 release
# DC #  - cuda-12-2.x86_64        # R535 (DataCenter Certified) - Long Term Stable
# DC #  - cuda-12-4.x86_64        # R550 (DataCenter Certified)
  - cuda-12-8.x86_64    # R570 (DataCenter Certified) - 2025Q2

# nVidia dependencies Software
defSWelX_nvidia_apis:  
  - libcuda.so.1
  - libEGL
  - libEGL_nvidia.so.0
  - libGLESv1_CM_nvidia.so.1
  - libGLESv2_nvidia.so.2
  - libGLX_nvidia.so.0
  - libnvidia-opencl.so.1
  - libOpenCL.so.1
  - libvdpau_nvidia.so.1
  - mesa-dri-drivers.x86_64
  - mesa-filesystem.x86_64
  - mesa-libEGL.x86_64
  - mesa-libgbm.x86_64
  - mesa-libGL.x86_64
  - mesa-libGLU.x86_64
  - mesa-libglapi.x86_64
  - mesa-vulkan-drivers.x86_64


###     RHEL9

defSWel9_nvidia_dvr:  570-dkms
# 2025Q1 # defSWel9_nvidia_dvr:  550-dkms

defSWel9_nvidia_deps:  "{{ defSWelX_nvidia_deps }}"

defSWel9_nvidia_cuda:  "{{ defSWelX_nvidia_cuda }}"

defSWel9_nvidia_apis:  "{{ defSWelX_nvidia_apis }}"


###     RHEL8

defSWel8_nvidia_dvr:  570-dkms
# 2025Q1 # defSWel8_nvidia_dvr:  550-dkms

defSWel8_nvidia_deps:  "{{ defSWelX_nvidia_deps }}"

defSWel8_nvidia_cuda:  "{{ defSWelX_nvidia_cuda }}"

defSWel8_nvidia_apis:  "{{ defSWelX_nvidia_apis }}"


###     RHEL7
# NOTE: RHEL7 is pre-modules (pre-Application Streams), and the playbook will likely NOT work

# R550-dkms is the FINAL release for RHEL7
defSWel7_nvidia_dvr:  550-dkms

defSWel7_nvidia_deps:
  - "@development"
  - dkms
  - kernel-devel

defSWel7_nvidia_apis:  
  - libcuda.so.1
  - libEGL
  - libEGL_nvidia.so.0
  - libGLESv1_CM_nvidia.so.1
  - libGLESv2_nvidia.so.2
  - libGLX_nvidia.so.0
  - libnvidia-opencl.so.1
  - libOpenCL.so.1
  - libvdpau_nvidia.so.1
  - mesa-dri-drivers.x86_64
  - mesa-filesystem.x86_64
  - mesa-libEGL.x86_64
  - mesa-libgbm.x86_64
  - mesa-libGL.x86_64
  - mesa-libGLU.x86_64
  - mesa-libglapi.x86_64
  - mesa-vulkan-drivers.x86_64



#####   HASHES USED IN PLAYBOOKS

###     RHEL9
defSWel9: { nvidia_dvr:  "{{ defSWel9_nvidia_dvr }}"
  , nvidia_deps:  "{{ defSWel9_nvidia_deps }}"
  , nvidia_cuda:  "{{ defSWel9_nvidia_cuda }}"
  , nvidia_apis:  "{{ defSWel9_nvidia_apis }}"
}

###     RHEL8
defSWel8: { nvidia_dvr:  "{{ defSWel8_nvidia_dvr }}"
  , nvidia_deps:  "{{ defSWel8_nvidia_deps }}"
  , nvidia_cuda:  "{{ defSWel8_nvidia_cuda }}"
  , nvidia_apis:  "{{ defSWel8_nvidia_apis }}"
}

###     RHEL7
defSWel7: { nvidia_dvr:  "{{ defSWel7_nvidia_dvr }}"
  , nvidia_deps:  "{{ defSWel7_nvidia_deps }}"
  , nvidia_cuda:  "{{ defSWel7_nvidia_cuda }}"
  , nvidia_apis:  "{{ defSWel7_nvidia_apis }}"
}


