---
#
#       ./roles/mask-fapusbg/tasks/main.yml
#       Ensure fapolicyd/usbguard are Masked (as well as Disabled/Stopped too)
#

- debug:
    msg:  "DEBUG:  {{ ansible_os_family}}{{ ansible_distribution_major_version }}({{ansible_distribution}}) /// myProd({{ myProd | default ('') }}) /// myRole({{ myRole | default('') }}) /// myCommit({{ myCommit | default('') }})"

- name: End play if not Enterprise Linux (EL) family
  meta: end_host
  when: ansible_os_family != "RedHat"

- name: Execute only on Non-production systems or all systems if Commit IS explicitly psased
  block:

    - name: Mask Troublesome Services By Default (so system will boot/be accessible)
      become: yes
      systemd:
        name: "{{ item }}"
        daemon_reload: no
        enabled: no
        masked:  yes      # Prevent it from starting for any dependency or check
        state:  stopped   # Ensure it's not running right now either
      with_items:
        - fapolicyd
        - usbguard
      ignore_errors: yes
      when:
        - ansible_kernel.find('Microsoft') == -1
        - ansible_distribution_major_version|int >= 7

  when: ( myProd is not defined ) or
        ( myProd is defined and myProd|bool != true ) or
        ( myProd is defined and myProd|bool == true and myCommit is defined and myCommit|bool == true )

